apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: keffa/book-catalog:latest
          env:
            - name: DATABASE_URL
              value: postgresql://task6_2_l7ed_user:JW9bLMWniWCVrfOEN0rCDbOeSMU5oPJt@dpg-crlenlrtq21c73eduu60-a.oregon-postgres.render.com/task6_2_l7ed
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
